# Generated by Django 4.2.3 on 2023-07-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regcomplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('flatblock', models.CharField(max_length=2, null=True)),
                ('flatno', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phoneno', models.IntegerField(null=True)),
                ('complainttitle', models.CharField(max_length=20)),
                ('complaintmedia', models.ImageField(upload_to='')),
                ('complaintdescription', models.TextField(max_length=500)),
            ],
        ),
    ]
