# Generated by Django 3.2.20 on 2023-07-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regcomplaints',
            name='flatblock',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
