# Generated by Django 3.2.20 on 2023-07-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_addmember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regcomplaints',
            new_name='Regcomplaint',
        ),
    ]
