# Generated by Django 3.2.20 on 2023-07-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_rename_regcomplaints_regcomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmember',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='regcomplaint',
            name='complaintmedia',
            field=models.ImageField(upload_to='images'),
        ),
    ]
