# Generated by Django 3.2.20 on 2023-08-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_auto_20230711_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_sub', models.CharField(max_length=100)),
                ('feed_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is_admin')),
                ('is_member', models.BooleanField(default=False, verbose_name='Is_member')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is_staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
