# Generated by Django 3.2.20 on 2023-08-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addmember',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
