# Generated by Django 3.2.20 on 2023-08-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_auto_20230809_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.IntegerField(choices=[(1, 'Electrical and Plumbing Issues'), (2, 'Drainage Issues'), (3, 'Construction and Issues')])),
            ],
        ),
    ]
