# Generated by Django 3.2.20 on 2023-08-09 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='regcomplaint',
            name='sections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.services'),
        ),
    ]
