# Generated by Django 3.2.20 on 2023-08-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_regcomplaint_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regcomplaint',
            name='sections',
        ),
        migrations.AddField(
            model_name='regcomplaint',
            name='complaint_type',
            field=models.CharField(choices=[('Elecricity', 'Elecricity'), ('Plumbing & Drainage', 'Plumbing & Drainage'), ('Construction', 'Construction')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
