# Generated by Django 3.2.20 on 2023-08-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_auto_20230810_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regcomplaint',
            name='complaint_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
