# Generated by Django 3.2.20 on 2023-08-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_alter_regcomplaint_complainttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
    ]
